@startuml

package Aggregation <<Rectangle>> {
    Car o-- Engine
}

package Composition <<Rectangle>> {
    House *-- Room
}

package Inheritance <<Rectangle>> {
    Pet <|-- Dog
}

package Implementation <<Rectangle>> {
    Interface <|.. Impl
}

package Association <<Rectangle>> {
    Animal --> SpeakInterface
}

package Dependency <<Rectangle>> {
    Processor ..> Data
}

@enduml