@startuml

interface Component
{
    + {Abstract} fnA()
    + {Abstract} fnB()
}

class ConcreteComp
{
    + fnA()
    + fnB()
}

Component <|.. ConcreteComp

Abstract Decorator
{
    + fnA()
    + fnB()
}

Component <|- Decorator
Component -o Decorator

Class ConcreteDecorA
{
    + fnA()
    + fnB()
}

Class ConcreteDecorB
{
    + fnA()
    + fnB()
}

Decorator <-- ConcreteDecorA
Decorator <-- ConcreteDecorB

@enduml
