#!/bin/bash

cmd="gsettings set org.gnome.shell.extensions.dash-to-dock"

key_values=(
"click-action 'quit'"
"preferred-monitor 0"
"force-straight-corner false"
"show-show-apps-button true"
"show-windows-preview true"
"animation-time 0.20000000000000001"
"scroll-action 'switch-workspace'"
"height-fraction 0.90000000000000002"
"activate-single-window true"
"running-indicator-dominant-color false"
"custom-theme-customize-running-dots true"
"minimize-shift true"
"show-apps-at-top false"
"pressure-threshold 100.0"
"show-delay 0.25"
"icon-size-fixed true"
"intellihide-mode 'ALL_WINDOWS'"
"customize-alphas false"
"apply-custom-theme false"
"hot-keys true"
"extend-height false"
"background-color '#ffffff'"
"shortcut-timeout 2.0"
"transparency-mode 'ADAPTIVE'"
"multi-monitor false"
"shortcut-text '<Super>q'"
"isolate-workspaces false"
"max-alpha 0.80000000000000004"
"app-shift-hotkey-10 \"['<Shift><Super>0']\""
"hide-delay 0.20000000000000001"
"show-favorites true"
"custom-theme-running-dots-border-color '#e95420'"
"custom-theme-running-dots-border-width 0"
"app-hotkey-10 \"['<Super>0']\""
"app-ctrl-hotkey-1 \"['<Ctrl><Super>1']\""
"app-ctrl-hotkey-2 \"['<Ctrl><Super>2']\""
"app-ctrl-hotkey-3 \"['<Ctrl><Super>3']\""
"app-ctrl-hotkey-4 \"['<Ctrl><Super>4']\""
"app-ctrl-hotkey-5 \"['<Ctrl><Super>5']\""
"app-ctrl-hotkey-6 \"['<Ctrl><Super>6']\""
"app-ctrl-hotkey-8 \"['<Ctrl><Super>8']\""
"app-ctrl-hotkey-9 \"['<Ctrl><Super>9']\""
"app-hotkey-1 \"['<Super>1']\""
"app-hotkey-2 \"['<Super>2']\""
"isolate-monitors false"
"app-hotkey-4 \"['<Super>4']\""
"app-hotkey-5 \"['<Super>5']\""
"app-hotkey-6 \"['<Super>6']\""
"app-hotkey-3 \"['<Super>3']\""
"app-hotkey-8 \"['<Super>8']\""
"app-hotkey-9 \"['<Super>9']\""
"custom-theme-shrink true"
"app-hotkey-7 \"['<Super>7']\""
"autohide true"
"app-ctrl-hotkey-7 \"['<Ctrl><Super>7']\""
"hotkeys-show-dock true"
"autohide-in-fullscreen true"
"dash-max-icon-size 48"
"background-opacity 0.80000000000000004"
"running-indicator-style 'DOTS'"
"dock-position 'LEFT'"
"middle-click-action 'launch'"
"scroll-switch-workspace true"
"app-ctrl-hotkey-10 \"['<Ctrl><Super>0']\""
"dock-fixed false"
"min-alpha 0.20000000000000001"
"shift-middle-click-action 'minimize'"
"show-running true"
"intellihide true"
"require-pressure-to-show false"
"unity-backlit-items false"
"custom-background-color false"
"custom-theme-running-dots-color '#e95420'"
"shortcut \"['<Super>q']\""
"app-shift-hotkey-1 \"['<Shift><Super>1']\""
"app-shift-hotkey-2 \"['<Shift><Super>2']\""
"app-shift-hotkey-3 \"['<Shift><Super>3']\""
"app-shift-hotkey-4 \"['<Shift><Super>4']\""
"app-shift-hotkey-5 \"['<Shift><Super>5']\""
"app-shift-hotkey-6 \"['<Shift><Super>6']\""
"app-shift-hotkey-7 \"['<Shift><Super>7']\""
"app-shift-hotkey-8 \"['<Shift><Super>8']\""
"app-shift-hotkey-9 \"['<Shift><Super>9']\""
"hotkeys-overlay true"
"bolt-support true"
"shift-click-action 'launch'"
"animate-show-apps true"
)

for i in ${!key_values[@]}
do
    eval "${cmd} ${key_values[${i}]}"
done

echo "Sortcuts for org.gnome.shell.extensions.dash-to-dock are set!"
